---
layout: article
title: January 4th Dev Update
published: true
date: 04.01.2018 09:00
---

=== projects

https://github.com/ethereumproject/emerald-wallet[**emerald-wallet**] addressed some issues found with RC1, including an initialization error, as well as various UI improvements.

Reusable visual components from **emerald-wallet** have been moved to https://github.com/ethereumproject/emerald-js-ui[**emerald-js-ui**].

https://github.com/ethereumproject/emerald-js[**emerald-js**], a young library of SDK-ish wallet logic, version is now at v0.0.21.

https://github.com/ethereumproject/emerald-cli/releases[**emerald-cli**] released v0.19.0, which fixes an HD path parsing bug.

https://github.com/ethereumproject/emerald-rs/releases[**emerald-rs**] released v0.19.0, including a public `mnemomic` module, an HD path parsing fix, and a few various minor upgrades.

https://github.com/ethereumproject/go-ethereum[**go-ethereum**] released https://github.com/ethereumproject/go-ethereum/releases/tag/v4.2.0[v4.2.0] including experimental support for https://github.com/ethereumproject/sputnikvm[SputnikVM], on-filesystem debug logging with automatic and configurable log compression and rotation, a rebuilt simpler UI, and support for user-configurable `GOMAXPROCS` environment variable.

https://github.com/ethereumproject/sputnikvm[**sputnikvm**] got some initial performance profiling and refactoring.

https://github.com/ethereumproject/etcommon-rs[**etcommon-rs**] implemented basic pruning and garbage collection support.


---

We are extremely grateful to *the many volunteers and members of our community* for
so many creative, thoughtful, and ongoing contributions.

---

> Isaac - https://github.com/whilei[Github: @whilei] - Slack: @ia


